### ISSUE TITLE
MicrosoftAutoUpdate.mobileconfig not showing anything.

### ISSUE THREAD

**Issue by mani2care** [kevinmcox/Configuration-Profiles#1]
I just downloaded the configuration profile "MicrosoftAutoUpdate.mobileconfig" and uploaded to jamf but its not showing anything.

<img width="434" alt="image" src="https://github.com/kevinmcox/Configuration-Profiles/assets/52978899/1624c3fc-d0ff-45e0-9fdc-d2aaba0b2103">

**Comment by mani2care** [comment]
And i noticed that other couple of id are missing in this configuration like defender ,teams 2.1 licensing help tool 


![IMG_7793](https://github.com/kevinmcox/Configuration-Profiles/assets/52978899/1b00ba96-3cf6-4c02-9720-f0b7612454f5)

**Comment by kevinmcox** [comment]
I don't use Jamf so can't comment on the first post.

Also these are intended to be examples and I don't keep them up-to-date at all times. I'll try to add those other identifiers in when I have time though, thanks.
